name: Main

on:
  push:
    branches: [ master ]
    tags: 
      - 'V*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 9.0.4 for x64
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
        #delete arch
        architecture: x64
    - name: Build with Maven
      uses: actions/cache@v2
      with: 
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
  pushDocker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with: 
          username: ${{ secrets.dockerhubUsername}}
          password: ${{ secrets.dockerhubPassword}}
          repository: pechov/bs2_labo6
          tags: latest
          tag_with_ref: true 

  Create Release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ GITHUB.RUN_NUMBER }}
            release_name: Release ${{ github.ref }}
            body: |
              Changes in this Release
              - First Change
              - Second Change
            draft: false
            prerelease: false
